server.port: 9090

spring.security.user:
  name: user
  password: test

spring.security.oauth2:
  client:
    client-id: iamclient
    client-secret: iamsecret
  resource:
    token-info-uri: http://localhost:8081/oauth/check_token

logging.level:
  org.springframework:
    security: debug
    boot: debug