server.port: 9090

security.oauth2.resource.jwt:
  key-store: 'classpath:keystore.jks'
  key-store-password: storepass
  key-alias: security
  key-password: keypass

logging.level:
  org.springframework:
    security: debug
    boot: debug